name: Bug Report
description: Log file is mandatory!
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!

  - type: checkboxes
    attributes:
      label: Prerequisites
      options:
        - label: I have searched the issue tracker to avoid opening a duplicate issue.
          required: true
        - label: I have read the [documentation](https://github.com/dobbelina/repository.dobbelina/wiki/Cumination:-Debug-Logging-and-Uploading) on how to create a debug log file.
          required: true

  - type: textarea
    attributes:
      label: Description
      description: Description of the bug
    validations:
      required: true

  - type: input
    attributes:
      label: Kodi version
    validations:
      required: true

  - type: input
    attributes:
      label: Cumination version
    validations:
      required: true

  - type: input
    attributes:
      label: Operating System and version
    validations:
      required: true

  - type: input
    attributes:
      label: URL to debug log file
      placeholder: https://paste.kodi.tv/
    validations:
      required: false
