name: Bug Report
description: Logfile Mandatory!
body:  
  - type: checkboxes
    attributes:
      label: Prerequisites.
      options:
        - label: I have searched the issue tracker to avoid opening a duplicate issue.
          required: true
        - label: I have read the [documentation](https://github.com/dobbelina/repository.dobbelina/wiki/Cumination:-Debug-Logging-and-Uploading) how to create a log file.
          required: true

  - type: textarea
    attributes:
      label: Description
      description: Description of the bug.
    validations:
      required: true

  - type: input
    attributes:
      label: What site/s are you having an issue with
    validations:
      required: true
    
  - type: input
    attributes:
      label: Cumination version
    validations:
      required: true

  - type: input
    attributes:
      label: Operating System and version
    validations:
      required: true
      
   - type: input
    attributes:
      label: URL to log file
    validations:
      required: false     
