blank_issues_enabled: false
contact_links:
  - name: Cumination Wiki Pages
    url: https://github.com/dobbelina/repository.dobbelina/wiki
    about: Information how to create a log file & Cloudflare challenges

